goal/urls.py
from django.conf.urls import url
from . import views

app_name='goal'
urlpatterns = [
    url(r'^$', views.task, name='task'),
    url(r'^daliy/$', views.daliy, name='daliy'),
    url(r'^newdaliy/$', views.newdaliy, name='newdaliy'),
    url(r'^newtask/$', views.newtask, name='newtask'),
    url(r'^deltoday/$', views.deltoday, name='deltoday'),
    url(r'^minitask/$', views.minitask, name='minitask'),
]

goal_beta1/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings

urlpatterns = [url(r'^admin/', admin.site.urls),url(r'^goal/',include('goal.urls')),]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns.append(url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}))

goal/models.py
from django.db import models
# Create your models here.

class day(models.Model):
# Create your models here.
	date=models.DateField(auto_now_add=True)
	starttime=models.TimeField()
	t1=models.CharField(max_length=200)
	t2=models.CharField(max_length=200)
	t3=models.CharField(max_length=200)
	t4=models.CharField(max_length=200)
	t5=models.CharField(max_length=200)
	t6=models.CharField(max_length=200)
	t7=models.CharField(max_length=200)
	t8=models.CharField(max_length=200)
	t9=models.CharField(max_length=200)
	t10=models.CharField(max_length=200)
	t11=models.CharField(max_length=200)
	t12=models.CharField(max_length=200)
	t13=models.CharField(max_length=200)
	t14=models.CharField(max_length=200)
	t15=models.CharField(max_length=200)
	t16=models.CharField(max_length=200)
	def __str__(self):
		return self.t1

		
class task(models.Model):
	text=models.CharField(max_length=200)
	topbranch=models.CharField(max_length=200)
	next=models.CharField(max_length=200)
	previous=models.CharField(max_length=200)
	startdate=models.DateField()
	completedate=models.DateField()
	progressvalue=models.IntegerField(default=0)
	audio = models.FileField(upload_to='goal/media', blank=True)
	def __str__(self):
		return self.text

goal/forms.py
from django import forms

class NameForm(forms.Form):
	text=forms.CharField(label='text',max_length=200)
	topbranch=forms.CharField(label='topbranch',max_length=200)
	next=forms.CharField(label='next',max_length=200)
	previous=forms.CharField(label='previous',max_length=200)
	startdate=forms.DateField(label='startdate')
	completedate=forms.DateField(label='completedate')
	progressvalue=forms.IntegerField(label='progressvalue')
	audio = forms.CharField(label='audio',max_length=200)
	
class DayForm(forms.Form):
	starttime=forms.TimeField(label='starttime')
	t1=forms.CharField(label='t1',max_length=200)
	t2=forms.CharField(label='t2',max_length=200)
	t3=forms.CharField(label='t3',max_length=200)
	t4=forms.CharField(label='t4',max_length=200)
	t5=forms.CharField(label='t5',max_length=200)
	t6=forms.CharField(label='t6',max_length=200)
	t7=forms.CharField(label='t7',max_length=200)
	t8=forms.CharField(label='t8',max_length=200)
	t9=forms.CharField(label='t9',max_length=200)
	t10=forms.CharField(label='t10',max_length=200)
	t11=forms.CharField(label='t11',max_length=200)
	t12=forms.CharField(label='t12',max_length=200)
	t13=forms.CharField(label='t13',max_length=200)
	t14=forms.CharField(label='t14',max_length=200)
	t15=forms.CharField(label='t15',max_length=200)
	t16=forms.CharField(label='t16',max_length=200)

goal/views.py
from django.shortcuts import render,get_list_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse
from .forms import NameForm,DayForm
from .models import task as tk,day as dy
import re,datetime,time
from datetime import date
from datetime import datetime as dt,timedelta

def diff_dates(date1, date2):
    return abs(date2-date1).days
	
# Create your views here.
def daliy(request):
	form=DayForm
	print('daliy')
	if (1):
		try:
			dd=dy.objects.filter(date=datetime.date.today())
			print('test')
			for d in dd:
				D=d
				print('1')
			ST=dt.strptime(str(D.starttime), '%H:%M:%S')
			print(ST)
			
			print(D)
			data=[]
			print(data)
			data.append({'time':str(dt.time(ST)),'task':D.t1})
			ST=ST+ timedelta(hours=1)
			data.append({'time':str(dt.time(ST)),'task':D.t2})
			ST=ST+ timedelta(hours=1)
			data.append({'time':str(dt.time(ST)),'task':D.t3})
			ST=ST+ timedelta(hours=1)
			data.append({'time':str(dt.time(ST)),'task':D.t4})
			ST=ST+ timedelta(hours=1)
			data.append({'time':str(dt.time(ST)),'task':D.t5})
			ST=ST+ timedelta(hours=1)
			data.append({'time':str(dt.time(ST)),'task':D.t6})
			ST=ST+ timedelta(hours=1)
			data.append({'time':str(dt.time(ST)),'task':D.t7})
			ST=ST+ timedelta(hours=1)
			data.append({'time':str(dt.time(ST)),'task':D.t8})
			ST=ST+ timedelta(hours=1)
			data.append({'time':str(dt.time(ST)),'task':D.t9})
			ST=ST+ timedelta(hours=1)
			data.append({'time':str(dt.time(ST)),'task':D.t10})
			ST=ST+ timedelta(hours=1)
			data.append({'time':str(dt.time(ST)),'task':D.t11})
			ST=ST+ timedelta(hours=1)
			data.append({'time':str(dt.time(ST)),'task':D.t12})
			ST=ST+ timedelta(hours=1)
			data.append({'time':str(dt.time(ST)),'task':D.t13})
			ST=ST+ timedelta(hours=1)
			data.append({'time':str(dt.time(ST)),'task':D.t14})
			ST=ST+ timedelta(hours=1)
			data.append({'time':str(dt.time(ST)),'task':D.t15})
			ST=ST+ timedelta(hours=1)
			data.append({'time':str(dt.time(ST)),'task':D.t16})
			print(data)
			localtime   = time.localtime()
			timeString  = time.strftime("%H:%M:%S", localtime)
			print(D.starttime,timeString)
			diff=dt.strptime(timeString, '%H:%M:%S')-dt.strptime(str(D.starttime), '%H:%M:%S')
			di=int((diff.seconds)/3600)
			print(data[di]['task'])
			print(diff.seconds,(3600-(diff.seconds)%3600)*1000,di)
			return render(request,'goal/daliy.html',{'data':data,'nxtt':(3600-(diff.seconds)%3600)*1000,'nxttk':data[di]['task']})
		except:
			print('except')
			tsl=tk.objects.exclude(next='NoNext').filter(previous='NoPrevious')
			ts=tk.objects.all()
			T=[]
			for d in ts:
				if ((d.progressvalue>99) and (d.next!='NoNext')):
					if(tk.objects.filter(next=d.next).exclude(progressvalue__lte=100)):
						tmp=tk.objects.filter(next=d.next).exclude(progressvalue__lte=100)
						for ttmp in tmp:
							T.append(ttmp.text)
					print('>99')
					print(T)
				if ((d.progressvalue<100) and (d.previous=='NoPrevious') and (d.topbranch!='Firsttask')):
					T.append(d.text)
					print('<100')
					print(T)
			
			return render(request,'goal/daliy.html',{'form':form,'task':T})
def minitask(request):
	return render(request,'goal/minitask.html')
			
def deltoday(request):
	try:
		dd=dy.objects.filter(date=datetime.date.today())
		dd.delete()
		return HttpResponseRedirect(reverse('goal:task'))
	except:
		print('no task yday')
		return HttpResponseRedirect(reverse('goal:task'))
def task(request):
	form=NameForm
	if (1):
		try:
			t=get_list_or_404(tk)
			print('try')
		except:
			print('except')
			return render(request,'goal/task.html',{'form':form})
		else:
			co=1
			for tt in t:
				if(datetime.date.today()>tt.startdate):
					pv=float(diff_dates(datetime.date.today(),tt.startdate))/float(diff_dates(tt.completedate,tt.startdate))
					val=tk.objects.get(text=tt.text)
					val.progressvalue=(pv*100)
				else:
					val=tk.objects.get(text=tt.text)
					val.progressvalue=0
				val.save()
			t=get_list_or_404(tk)
			T=[]
			name=[]
			id=[]
			iddic={}
			i=0
			for tt in t:
				if tt.topbranch not in name:
					name.append(tt.topbranch)
					id.append('id'+str(i))
					i+=1
				if tt.text not in name:
					name.append(tt.text)
					id.append('id'+str(i))
					i+=1
				if tt.next not in name:
					name.append(tt.next)
					id.append('id'+str(i))
					i+=1
				if tt.previous not in name:
					name.append(tt.previous)
					id.append('id'+str(i))
					i+=1
			for tt in range(len(id)):
				iddic[name[tt]]=id[tt]
			for tt in t:
				T.append({'text':tt.text,'topbranch':tt.topbranch,
				'next':tt.next,'previous':tt.previous,
				'startdate':(tt.startdate).isoformat(),'completedate':(tt.completedate).isoformat(),
				'progressvalue':tt.progressvalue,'audio':tt.audio,
				'txtid':iddic[tt.text],'tbid':iddic[tt.topbranch],'nxtid':iddic[tt.next],
				'preid':iddic[tt.previous]})
			print(T)	
			for t in range(len(T)):
				if T[t]['text']=='Get more  friends':
					T[t]['progressvalue']=90
			return render(request,'goal/task.html',{'form':form,'co':co,'t':T})
def newdaliy(request):
	if request.method=="POST":
		form=DayForm(request.POST)
		print('test')
		print(form.errors)
		if form.is_valid():
			print('test')
			ST=form.cleaned_data['starttime']
			T1=form.cleaned_data['t1']
			T2=form.cleaned_data['t2']
			T3=form.cleaned_data['t3']
			T4=form.cleaned_data['t4']
			T5=form.cleaned_data['t5']
			T6=form.cleaned_data['t6']
			T7=form.cleaned_data['t7']
			T8=form.cleaned_data['t8']
			T9=form.cleaned_data['t9']
			T10=form.cleaned_data['t10']
			T11=form.cleaned_data['t11']
			T12=form.cleaned_data['t12']
			T13=form.cleaned_data['t13']
			T14=form.cleaned_data['t14']
			T15=form.cleaned_data['t15']
			T16=form.cleaned_data['t16']
			print(ST,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16)
			d=dy(starttime=ST,t1=T1,t2=T2,t3=T3,t4=T4,t5=T5,t6=T6,t7=T7,t8=T8,t9=T9,t10=T10,t11=T11,t12=T12,t13=T13,t14=T14,t15=T15,t16=T16)
			d.save()
			return HttpResponseRedirect(reverse('goal:daliy'))
def newtask(request):
	print('test')
	if request.method=="POST":
		form=NameForm(request.POST)
		print(form.errors)
		if form.is_valid():
			txt=form.cleaned_data['text']
			tb=form.cleaned_data['topbranch']
			nxt=form.cleaned_data['next']
			pre=form.cleaned_data['previous']
			sdte=form.cleaned_data['startdate']
			cdte=form.cleaned_data['completedate']
			pv=form.cleaned_data['progressvalue']
			au=form.cleaned_data['audio']
			au='goal/media'+au.replace('\\','/')
			try:
				t=tk.objects.get(text=txt)
				t.delete()
				try:
					t=tk.objects.get(text=pre)
					t.next=txt
					t.save()
					t=tk.objects.get(previous=pre)
					print('found',pre)
					t.previous=txt
					t.save()
					t=tk(text=txt,topbranch=tb,next=nxt,previous=pre,progressvalue=pv,startdate=sdte,completedate=cdte,audio=au)
					t.save()
				except:
					print('not found')
					t=tk(text=txt,topbranch=tb,next=nxt,previous=pre,progressvalue=pv,startdate=sdte,completedate=cdte,audio=au)
					t.save()
			except:
				try:
					t=tk.objects.get(text=pre)
					t.next=txt
					t.save()
					t=tk.objects.get(previous=pre)
					print('found',pre)
					t.previous=txt
					t.save()
					t=tk(text=txt,topbranch=tb,next=nxt,previous=pre,progressvalue=pv,startdate=sdte,completedate=cdte,audio=au)
					t.save()
				except:
					print('not found')
					t=tk(text=txt,topbranch=tb,next=nxt,previous=pre,progressvalue=pv,startdate=sdte,completedate=cdte,audio=au)
					t.save()
			
			print('ok')
			return HttpResponseRedirect(reverse('goal:task'))
		else:
			print('not ok')

goal/templates/goal/daliy.html
<!DOCTYPE html>
<meta charset="UTF-8">
	<html>
		<head><title>Daliy Task</title>
			<style>
				body{
				background: rgba(200,173,127,0.1) ;width: 98%;margin-left: auto ;
				margin-right: auto ;opacity:1;}

				.button,button{
				border:1px solid #393b3e;-webkit-box-shadow: #737373 0px 1px 5px ;text-transform:uppercase;
				-moz-box-shadow: #737373 0px 1px 5px ; box-shadow: #737373 0px 1px 5px ;
				-webkit-border-radius: 23px; -moz-border-radius: 23px;
				border-radius: 23px;font-size:14px;font-family:arial, helvetica, sans-serif; padding: 0px 5px 0px 5px; text-decoration:none; display:inline-block;text-shadow: 0px 1px 0 rgba(10,10,10,0.5);font-weight:bold; color: #8C8C8C;
				background-color: #515459; background-image: -webkit-gradient(linear, left top, left bottom, from(#515459), to(#3B3C40));
				background-image: -webkit-linear-gradient(top, #515459, #3B3C40);
				background-image: -moz-linear-gradient(top, #515459, #3B3C40);
				background-image: -ms-linear-gradient(top, #515459, #3B3C40);
				background-image: -o-linear-gradient(top, #515459, #3B3C40);
				background-image: linear-gradient(to bottom, #515459, #3B3C40);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#515459, endColorstr=#3B3C40);
				}

				.button,button:hover{
				border:1px solid #393b3e;text-transform:uppercase;
				background-color: #3B3C40; background-image: -webkit-gradient(linear, left top, left bottom, from(#3B3C40), to(#202124));
				background-image: -webkit-linear-gradient(top, #3B3C40, #202124);
				background-image: -moz-linear-gradient(top, #3B3C40, #202124);
				background-image: -ms-linear-gradient(top, #3B3C40, #202124);
				background-image: -o-linear-gradient(top, #3B3C40, #202124);
				background-image: linear-gradient(to bottom, #3B3C40, #202124);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#3B3C40, endColorstr=#202124);
				}
				.task{border-radius: 10px;border-style:solid;border-left-color:rgba(48,213,200,0.05); 
				border-top-color:rgba(48,213,200,0.05);
				border-right-color:rgba(212,175,55,0.05);
				border-bottom-color:rgba(212,175,55,0.05);
				box-shadow: inset 0 0 10vw rgba(255,255,255,0.4);
				background-image:
				-webkit-linear-gradient(left top, 
				rgba(48,213,200,0.2), 
				rgba(212,175,55,0.2));}
				
				progress[value]::-webkit-progress-bar {
				background-color: #eee;
				border-radius: 2px;
				width:300%;
				height:200%;
				box-shadow: 0 2px 5px rgba(0, 0, 0, 0.25) inset;
				}

				progress[value]::-webkit-progress-value {
				background-image:
				-webkit-linear-gradient(-45deg, 
				transparent 33%, rgba(0, 0, 0, .1) 33%, 
				rgba(255,255, 255, .1) 66%, transparent 66%),
				-webkit-linear-gradient(top, 
				rgba(255, 255, 255, .25), 
				rgba(0, 0, 0, .25)),
				-webkit-linear-gradient(left, #09c, #f44);

				border-radius: 2px; 
				background-size: 35px 20px, 100% 100%, 100% 100%;
				}

				ul.sidenav {
				list-style-type: none;
				margin: 0;
				padding: 0;
				width: 25%;
				background-color: #f1f1f1;
				position: fixed;
				height: 100%;
				overflow: auto;
				}

				ul.sidenav li a {
				display: block;
				color:rgb(166,123,91);
				padding: 8px 16px;
				text-decoration: none;
				border-right: 1px solid rgb(166,123,91);


				}

				ul.sidenav li a.active {
				background-color: rgba(255,176,31,0.7);
				color: #000;
				}

				ul.sidenav li a:hover:not(.active) {
				background-color: #555;
				color: white;
				}


				@media screen and (max-width: 1050px){
				ul.sidenav {
				width:100%;
				height:auto;
				position:relative;
				}
				ul.sidenav li a {
				float: left;
				padding: 15px;
				}
				}

				@media screen and (max-width: 400px){
				ul.sidenav li a {
				text-align: center;
				float: none;
				}
				}

				label{text-transform:uppercase;color:rgb(166,123,91);
				padding: 8px 16px;
				text-decoration: none;
				border: 1px solid rgb(166,123,91);}
				
				table {
  border-spacing: 0.5rem;}
}
td, th {width: 4rem;
  height: 2rem;
  border: 1px solid #ccc;
  text-align: center;
}td{background:rgba(255,176,31,0.7);text-align: center;}
th {
  background: lightblue;
  border-color: black;color:rgb(166,123,91);
}
			</style>
			</head>
		<body>
		<div id='body'>
		<div style="text-align:center;padding:10px;text-transform:uppercase;">
					<a href="{% url 'goal:daliy' %}" style="font-family:Impact, Charcoal, sans-serif;font-size:800%;text-aline:center;text-decoration:none;color:rgba(255,110,94,0.8);">My Goal<span style="color:rgba(255,176,31,0.7)">s</span></a>
					<div style="color:rgba(202,31,123,0.5);font-family:'Comic Sans MS', cursive, sans-serif"> The best application to reach your goal
					</div></div><hr>
					<ul class="sidenav">
						<li><a class="active" href="{% url 'goal:daliy' %}">Daliy</a></li>
						<li><a href="{% url 'goal:task' %}">Task</a></li>
						<li style="float:right;border-left: 1px solid rgb(166,123,91);"><a class="active" href="#about">About(not ready)</a></li>
					</ul><hr>
		{%if form %}
		<div id='taskform' style="z-index:10;display:block;width: 80%;margin-left: auto;margin-right: auto ;">
						<div style='display:inline;float:left'>
						<form action="{% url 'goal:newdaliy' %}" method="post">
									{% csrf_token %}{% for field in form %}
									<div class="fieldWrapper" >
										{{ field.errors }}
										{{ field.label_tag }} {{ field }}
										{% if field.help_text %}
										<p class="help">{{ field.help_text|safe }}</p>
										{% endif %}
									</div><br/>
									{% endfor %}
									<input type="submit" id='in' value="Submit" /></form>
								<Button style='float:right'  onclick='restart()'>Restart</button>
				</div>
				<div  style="display:inline;float:right;"><b>paste one for the following<br/></b>
					{% for t in task %}<button onclick='inn("{{t}}")'>{{t}}</button><br/><br/>{%endfor%}
					<button onclick='inn("Break")'>Break</button><br/><br/>
					<button onclick='inn("Planning")'>Planning</button><br/><br/>
					<button onclick='inn("Socialize")'>Socialize</button><br/><br/>
				</div>
			</div>
				<script>
				document.getElementById('id_starttime').type='time';
				document.getElementById('id_starttime').step='1800';
				document.getElementById('id_starttime').value='06:30';
				var input=1;
				function restart(){input=1;}
				function inn(valu){
					document.getElementById("id_t".concat(input)).value=valu;
					input+=1;
				}</script>
				{%else%}
				<div><div style='display:inline;float:right;padding-right: 10%'>
				<form action="{% url 'goal:deltoday' %}" method="post">
				{% csrf_token %}<input type="submit" id='in' value="Reset Daliy Task" /></form>
				</div>
				<div style='display:inline;width: 90%;margin-left: auto;margin-right: auto '>
					<table style='text-aline:center;min-width:50%;margin-right: auto;'>
					<tr><th>Time</th><th>Task</th></tr>
					{% for d in data%}
					<tr><th>{{d.time}}</th><td>{{d.task}}</td></tr>
					{%endfor%}
					</table>
				</div>
					<button onclick="notifyMe()">Notify me!</button>
				</div>
				<script>
				document.addEventListener('DOMContentLoaded', function () {
  if (!Notification) {
    alert('Desktop notifications not available in your browser. Try Chromium.'); 
    return;
  }

  if (Notification.permission !== "granted")
    Notification.requestPermission();
	
	var notification = new Notification('Remember-Remember', {
      icon: 'http://cdn.kercommunications.com/wp-content/uploads/artificial-intelligence.png',
      body: "{{nxttk}} \n Keep Going",
    });

    notification.onclick = function () {window.open("{% url 'goal:minitask' %}");      
    };
});
setTimeout(function(){location.reload();}, {{nxtt}});

</script>
				{% endif%}
		</div>
		</body>
					</html>

goal/templates/goal/minitask.html
<!DOCTYPE html>
<meta charset="UTF-8">
	<html>
		<head><title>Mini Task</title>
		<style>body{background: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/652/confectionary.png) repeat; }</style>
		</head>
		<body>
		<div id='minitask' style='border:5px solid rgba(255,176,31,0.7);z-index:1;border-radius: 50px/20px;height:200px;width:80%;margin-left:auto;margin-right:auto;background:white;text-align:center;font-size:50px'>
		<label style='font-family:Impact, Charcoal, sans-serif;'>MiniTasker</label><br/>
		<label id='co'>Count</label><br/>
		<label id='tt' style=''><input id='txt' type='text'/></label><br/>
		<button id='but' onclick='toggle()'>Start</button>
		</div>
		
		
		<script>
			var c=0;
var timer_is_on=false;
function displayCount() {
	if(c>1200){
    document.getElementById('co').innerHTML="<label style='color:red'>"+c+"</label>";}
	else{
	document.getElementById('co').innerHTML=c;}
	}

function count() {
    if(timer_is_on) {
        c=c+1;
        displayCount();
    }
}
	
function toggle() {
    if(timer_is_on) {
       timer_is_on = false;
	   document.getElementById('tt').style.opacity='0';
       document.getElementById('tt').innerHTML="<input  id='txt' type='text'/>";
	   document.getElementById('tt').style.opacity='1';
	   document.getElementById('co').innerHTML='Count';
	   document.getElementById('but').innerHTML='Start';
	   c=0;
    } else {
       timer_is_on = true;
	   document.getElementById('tt').innerHTML=document.getElementById('txt').value;
	   document.getElementById('but').innerHTML='Stop';
	   
    }                   
}
var interval = setInterval(count,1000);


		</script>
		</body>
	</html>